### ISSUE TITLE
Exit Code -1 ; Index out of bounds for length - Game won't start up

### ISSUE THREAD

**Issue by btocker1127** [AllTheMods/ATM-8#1044]
Game started crashing yesterday, tried updating the version, not sure how to fix it
 
[Crash Report ATM 8.txt](https://github.com/AllTheMods/ATM-8/files/10933940/Crash.Report.ATM.8.txt)

First couple of lines from the crash report: 
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?] {}
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?] {}
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?] {}
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?] {re:mixin}
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?] {re:mixin}
	at reliquary.items.util.FilteredItemStackHandler.getStackInSlot(FilteredItemStackHandler.java:124) ~[reliquary-1.19.2-2.0.20.1166.jar%23724!/:1.19.2-2.0.20.1166] {re:classloading}

**Comment by TakeyaSaito** [comment]
I have this exact same problem, can't launch, just installed

**Comment by osirus31** [comment]
I am able to fix this by "re-installing" ATM8 via Curseforge (switch versions to the same version you are already on) and repairing the profile.
