### ISSUE TITLE
Sophisticated Backback has become bugged and cannot be opened

### ISSUE THREAD

**Issue by e-SonOfAnder** [AllTheMods/ATM-8#1067]
Modpack Version: 1.0.9
No mods added or removed
Windows 11, using Curseforge app for instance/modpack management

Found another report of what appears to be this same issue on Reddit: https://www.reddit.com/r/allthemods/comments/10loozj/sophisticated_backpacks_bug_help/

This is a recently started save, but during my session earlier this evening, hitting the open backpack hotkey just stopped working out of the blue. Nothing specific was done to trigger it - did not put anything in to, or take anything out of the backpack. The backpack is completely bugged, and cannot be opened even by right clicking it from the main hand, or by placing it on the ground and attempting to open it. I am attaching my latest.log, because I do see some unusual errors coming through constantly that do eventually filter up through the Sophisticated Backpacks mod, though it is unclear if they are 100% related to what I am seeing/experiencing.

[latest.log](https://github.com/AllTheMods/ATM-8/files/10953876/latest.log)

Example:
[22:24:19] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@23498dbe, suppressing error
java.lang.NullPointerException: Cannot invoke "blusunrize.immersiveengineering.common.register.IEItems$ItemRegObject.m_5456_()" because the return value of "java.util.Map.get(Object)" is null
	at blusunrize.immersiveengineering.common.crafting.ShaderBagRecipe.matches(ShaderBagRecipe.java:45) ~[ImmersiveEngineering-1.19.2-9.1.0-156.jar%23633!/:?]
	at blusunrize.immersiveengineering.common.crafting.ShaderBagRecipe.m_5818_(ShaderBagRecipe.java:26) ~[ImmersiveEngineering-1.19.2-9.1.0-156.jar%23633!/:?]
	at shadows.fastsuite.AuxRecipeManager$RecipeNode.matches(AuxRecipeManager.java:190) ~[FastSuite-1.19.2-4.0.0.jar%23602!/:4.0.0]
	at shadows.fastsuite.AuxRecipeManager$LinkedRecipeList.findFirstMatch(AuxRecipeManager.java:160) ~[FastSuite-1.19.2-4.0.0.jar%23602!/:4.0.0]
	at shadows.fastsuite.AuxRecipeManager.m_44015_(AuxRecipeManager.java:64) ~[FastSuite-1.19.2-4.0.0.jar%23602!/:4.0.0]
	at net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer.updateCraftingResult(CraftingUpgradeContainer.java:112) ~[sophisticatedcore-1.19.2-0.5.38.203.jar%23759!/:1.19.2-0.5.38.203]
	at net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer.onCraftMatrixChanged(CraftingUpgradeContainer.java:101) ~[sophisticatedcore-1.19.2-0.5.38.203.jar%23759!/:1.19.2-0.5.38.203]
	at net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer.onInit(CraftingUpgradeContainer.java:97) ~[sophisticatedcore-1.19.2-0.5.38.203.jar%23759!/:1.19.2-0.5.38.203]
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.addUpgradeSettingsContainers(StorageContainerMenuBase.java:125) ~[sophisticatedcore-1.19.2-0.5.38.203.jar%23759!/:1.19.2-0.5.38.203]
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.initSlotsAndContainers(StorageContainerMenuBase.java:111) ~[sophisticatedcore-1.19.2-0.5.38.203.jar%23759!/:1.19.2-0.5.38.203]
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.<init>(StorageContainerMenuBase.java:102) ~[sophisticatedcore-1.19.2-0.5.38.203.jar%23759!/:1.19.2-0.5.38.203]
	at net.p3pp3rf1y.sophisticatedbackpacks.common.gui.BackpackContainer.<init>(BackpackContainer.java:36) ~[sophisticatedbackpacks-1.19.2-3.18.40.779.jar%23758!/:1.19.2-3.18.40.779]
	at net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.lambda$use$9(BackpackItem.java:287) ~[sophisticatedbackpacks-1.19.2-3.18.40.779.jar%23758!/:1.19.2-3.18.40.779]
	at net.minecraft.world.SimpleMenuProvider.m_7208_(SimpleMenuProvider.java:25) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraftforge.network.NetworkHooks.openScreen(NetworkHooks.java:201) ~[forge-1.19.2-43.2.3-universal.jar%23816!/:?]
	at net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.m_7203_(BackpackItem.java:287) ~[sophisticatedbackpacks-1.19.2-3.18.40.779.jar%23758!/:1.19.2-3.18.40.779]
	at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:266) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:286) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1089) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by James103** [comment]
Please update Immersive Engineering to the latest version: https://modrinth.com/mod/immersiveengineering/versions?g=1.19.2

**Comment by e-SonOfAnder** [comment]
Confirmed this has fixed the issue.
