### ISSUE TITLE
Ars Nouveau Inscribing Table crashes the server

### ISSUE THREAD

**Issue by FChapeau** [AllTheMods/ATM-8#1086]
I run a server with a friend. We placed an Inscribing Table from Ars Nouveau and upon using it, the server crashed. Any attempt to log back in caused the same error to occur.

```
2023-03-16 16:05:28 | ---- Minecraft Crash Report ----
-- | --
  |   | 2023-03-16 16:05:28 | // I feel sad now :(
  |   | 2023-03-16 16:05:28 |  
  |   | 2023-03-16 16:05:28 | Time: 2023-03-16 20:05:28
  |   | 2023-03-16 16:05:28 | Description: Ticking block entity
  |   | 2023-03-16 16:05:28 |  
  |   | 2023-03-16 16:05:28 | java.lang.NullPointerException: Ticking block entity
  |   | 2023-03-16 16:05:28 | at java.util.Objects.requireNonNull(Unknown Source) ~[?:?] {re:mixin}
  |   | 2023-03-16 16:05:28 | at com.smashingmods.alchemylib.api.blockentity.processing.AbstractInventoryBlockEntity.getCapability(AbstractInventoryBlockEntity.java:59) ~[alchemylib-1.19.2-1.0.20.jar%23437!/:1.19.2-1.0.20] {re:classloading}
  |   | 2023-03-16 16:05:28 | at com.hollingsworth.arsnouveau.common.block.tile.ScribesTile.checkInventories(ScribesTile.java:127) ~[ars_nouveau-1.19.2-3.12.3.jar%23455!/:3.12.3] {re:classloading}
  |   | 2023-03-16 16:05:28 | at com.hollingsworth.arsnouveau.common.block.tile.ScribesTile.tick(ScribesTile.java:102) ~[ars_nouveau-1.19.2-3.12.3.jar%23455!/:3.12.3] {re:classloading}
  |   | 2023-03-16 16:05:28 | at com.hollingsworth.arsnouveau.common.block.ITickable.tick(ITickable.java:20) ~[ars_nouveau-1.19.2-3.12.3.jar%23455!/:3.12.3] {re:classloading}
  |   | 2023-03-16 16:05:28 | at com.hollingsworth.arsnouveau.common.block.ITickableBlock.lambda$getTicker$0(ITickableBlock.java:16) ~[ars_nouveau-1.19.2-3.12.3.jar%23455!/:3.12.3] {re:classloading}
  |   | 2023-03-16 16:05:28 | at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:classloading,pl:accesstransformer:B}
  |   | 2023-03-16 16:05:28 | at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:classloading,pl:accesstransformer:B}
  |   | 2023-03-16 16:05:28 | at net.minecraft.world.level.Level.redirect$bfk000$redirectTick(Level.java:2538) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
  |   | 2023-03-16 16:05:28 |  
  |   | 2023-03-16 16:05:28 |  
  |   | 2023-03-16 16:05:28 | A detailed walkthrough of the error, its code path and all known details is as follows:
  |   | 2023-03-16 16:05:28 | ---------------------------------------------------------------------------------------
  |   | 2023-03-16 16:05:28 |  
  |   | 2023-03-16 16:05:28 | -- Head --
  |   | 2023-03-16 16:05:28 | Thread: Server thread
  |   | 2023-03-16 16:05:28 | Stacktrace:
  |   | 2023-03-16 16:05:28 | at java.util.Objects.requireNonNull(Unknown Source) ~[?:?] {re:mixin}
  |   | 2023-03-16 16:05:28 | at com.smashingmods.alchemylib.api.blockentity.processing.AbstractInventoryBlockEntity.getCapability(AbstractInventoryBlockEntity.java:59) ~[alchemylib-1.19.2-1.0.20.jar%23437!/:1.19.2-1.0.20] {re:classloading}
  |   | 2023-03-16 16:05:28 | at com.hollingsworth.arsnouveau.common.block.tile.ScribesTile.checkInventories(ScribesTile.java:127) ~[ars_nouveau-1.19.2-3.12.3.jar%23455!/:3.12.3] {re:classloading}
  |   | 2023-03-16 16:05:28 | at com.hollingsworth.arsnouveau.common.block.tile.ScribesTile.tick(ScribesTile.java:102) ~[ars_nouveau-1.19.2-3.12.3.jar%23455!/:3.12.3] {re:classloading}
  |   | 2023-03-16 16:05:28 | at com.hollingsworth.arsnouveau.common.block.ITickable.tick(ITickable.java:20) ~[ars_nouveau-1.19.2-3.12.3.jar%23455!/:3.12.3] {re:classloading}
  |   | 2023-03-16 16:05:28 | at com.hollingsworth.arsnouveau.common.block.ITickableBlock.lambda$getTicker$0(ITickableBlock.java:16) ~[ars_nouveau-1.19.2-3.12.3.jar%23455!/:3.12.3] {re:classloading}
  |   | 2023-03-16 16:05:28 | at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:classloading,pl:accesstransformer:B}
  |   | 2023-03-16 16:05:28 | at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:classloading,pl:accesstransformer:B}
  |   | 2023-03-16 16:05:28 | at net.minecraft.world.level.Level.redirect$bfk000$redirectTick(Level.java:2538) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | -- Block entity being ticked --
  |   | 2023-03-16 16:05:28 | Details:
  |   | 2023-03-16 16:05:28 | Name: ars_nouveau:scribes_table // com.hollingsworth.arsnouveau.common.block.tile.ScribesTile
  |   | 2023-03-16 16:05:28 | Block: Block{ars_nouveau:scribes_table}[facing=west,part=head]
  |   | 2023-03-16 16:05:28 | Block location: World: (500,79,-163), Section: (at 4,15,13 in 31,4,-11; chunk contains blocks 496,-64,-176 to 511,319,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
  |   | 2023-03-16 16:05:28 | Block: Block{ars_nouveau:scribes_table}[facing=west,part=head]
  |   | 2023-03-16 16:05:28 | Block location: World: (500,79,-163), Section: (at 4,15,13 in 31,4,-11; chunk contains blocks 496,-64,-176 to 511,319,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
  |   | 2023-03-16 16:05:28 | Stacktrace:
  |   | 2023-03-16 16:05:28 | at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:classloading,pl:accesstransformer:B}
  |   | 2023-03-16 16:05:28 | at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:classloading,pl:accesstransformer:B}
  |   | 2023-03-16 16:05:28 | at net.minecraft.world.level.Level.redirect$bfk000$redirectTick(Level.java:2538) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
  |   | 2023-03-16 16:05:28 |  
  |   | 2023-03-16 16:05:28 |  
  |   | 2023-03-16 16:05:28 | -- Affected level --
  |   | 2023-03-16 16:05:28 | Details:
  |   | 2023-03-16 16:05:28 | All players: 1 total; [ServerPlayer['Heart_of_Silver'/1018, l='ServerLevel[world]', x=500.94, y=79.00, z=-160.69]]
  |   | 2023-03-16 16:05:28 | Chunk stats: 3137
  |   | 2023-03-16 16:05:28 | Level dimension: minecraft:overworld
  |   | 2023-03-16 16:05:28 | Level spawn location: World: (-16,106,-48), Section: (at 0,10,0 in -1,6,-3; chunk contains blocks -16,-64,-48 to -1,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
  |   | 2023-03-16 16:05:28 | Level time: 13620020 game time, 13780437 day time
  |   | 2023-03-16 16:05:28 | Level name: world
  |   | 2023-03-16 16:05:28 | Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  |   | 2023-03-16 16:05:28 | Level weather: Rain time: 19519 (now: false), thunder time: 116398 (now: false)
  |   | 2023-03-16 16:05:28 | Known server brands: forge
  |   | 2023-03-16 16:05:28 | Level was modded: true
  |   | 2023-03-16 16:05:28 | Level storage version: 0x04ABD - Anvil
  |   | 2023-03-16 16:05:28 | Stacktrace:
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
  |   | 2023-03-16 16:05:28 | at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
```

**Comment by Mitchell5200** [comment]
Same crash log as https://github.com/baileyholl/Ars-Nouveau/issues/893
