### ISSUE TITLE
unsusal crash with v1.0.18 (server)

### ISSUE THREAD

**Issue by cainp** [AllTheMods/ATM-8#1376]
crash report: 

Description: Exception in server tick loop

java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
	at com.electronwill.nightconfig.core.file.FileWatcher$WatchedDir.<init>(FileWatcher.java:220) ~[core-3.6.4.jar%2356!/:?] {}
	at com.electronwill.nightconfig.core.file.FileWatcher$WatchedDir.<init>(FileWatcher.java:210) ~[core-3.6.4.jar%2356!/:?] {}
	at com.electronwill.nightconfig.core.file.FileWatcher.lambda$addWatch$0(FileWatcher.java:81) ~[core-3.6.4.jar%2356!/:?] {}
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?] {}
	at com.electronwill.nightconfig.core.file.FileWatcher.addWatch(FileWatcher.java:81) ~[core-3.6.4.jar%2356!/:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:51) ~[fmlcore-1.19.2-43.2.11.jar%23776!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60) ~[fmlcore-1.19.2-43.2.11.jar%23776!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.19.2-43.2.11.jar%23776!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.19.2-43.2.11.jar%23776!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:90) ~[forge-1.19.2-43.2.11-universal.jar%23780!/:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:163) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:62) ~[?:?] {}
	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47) ~[?:?] {}
	at com.electronwill.nightconfig.core.file.FileWatcher$WatchedDir.<init>(FileWatcher.java:218) ~[core-3.6.4.jar%2356!/:?] {}
	... 15 more

**Comment by jaynotgay** [comment]
You need to modify the fs.inotify.max_user_watches parameter in your sysctl config. You can do this by running the following commands: 

echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

modify the nofile parameter in the /etc/security/limits.conf
