### ISSUE TITLE
[1.0.19b]Server crashed when i was in nether, the report shows  NullPointerException

### ISSUE THREAD

**Issue by liangfan-e** [AllTheMods/ATM-8#1427]
java.lang.NullPointerException: Cannot read field "f_46443_" because "this.f_58857_" is null
	at com.simibubi.create.content.contraptions.base.GeneratingKineticTileEntity.updateGeneratedRotation(GeneratingKineticTileEntity.java:95) ~[create-1.19.2-0.5.0.i.jar%23519!/:0.5.0.i] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at com.simibubi.create.foundation.block.ITE.withTileEntityDo(ITE.java:29) ~[create-1.19.2-0.5.0.i.jar%23519!/:0.5.0.i] {re:mixin,re:computing_frames,re:classloading}
	at com.simibubi.create.content.contraptions.components.waterwheel.WaterWheelBlock.updateWheelSpeed(WaterWheelBlock.java:144) ~[create-1.19.2-0.5.0.i.jar%23519!/:0.5.0.i] {re:classloading}
	at com.simibubi.create.content.contraptions.components.waterwheel.WaterWheelBlock.m_7417_(WaterWheelBlock.java:71) ~[create-1.19.2-0.5.0.i.jar%23519!/:0.5.0.i] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60728_(BlockBehaviour.java:730) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin,pl:mixin:APP:radon.mixins.json:block.MixinAbstractBlockState,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:byg.mixins.json:common.block.MixinBlockBehaviourBlockStateBase,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.m_74488_(StructureTemplate.java:358) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.phys.shapes.DiscreteVoxelShape.m_82812_(DiscreteVoxelShape.java:225) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:DiscreteVSAccess,pl:mixin:A}
	at net.minecraft.world.phys.shapes.DiscreteVoxelShape.m_82810_(DiscreteVoxelShape.java:203) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:DiscreteVSAccess,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.m_74510_(StructureTemplate.java:348) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at potionstudios.byg.common.world.feature.gen.overworld.trees.util.BYGAbstractTreeFeature.placeTree(BYGAbstractTreeFeature.java:583) ~[Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.1.jar%23657!/:2.0.1.1] {re:classloading}
	at potionstudios.byg.common.world.feature.gen.overworld.trees.util.BYGAbstractTreeFeature.place(BYGAbstractTreeFeature.java:496) ~[Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.1.jar%23657!/:2.0.1.1] {re:classloading}
	at potionstudios.byg.common.world.feature.gen.overworld.trees.util.BYGAbstractTreeFeature.m_142674_(BYGAbstractTreeFeature.java:483) ~[Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.1.jar%23657!/:2.0.1.1] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.Feature.m_225028_(Feature.java:154) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,re:classloading,pl:mixin:APP:farmersdelight.mixins.json:KeepRichSoilGiantTreeMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(ConfiguredFeature.java:27) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ConfiguredFeatureMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226362_(PlacedFeature.java:56) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226368_(PlacedFeature.java:55) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226357_(PlacedFeature.java:40) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.levelgen.feature.WeightedPlacedFeature.m_225367_(WeightedPlacedFeature.java:28) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.RandomSelectorFeature.m_142674_(RandomSelectorFeature.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.Feature.m_225028_(Feature.java:154) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,re:classloading,pl:mixin:APP:farmersdelight.mixins.json:KeepRichSoilGiantTreeMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(ConfiguredFeature.java:27) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ConfiguredFeatureMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226362_(PlacedFeature.java:56) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:364) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226368_(PlacedFeature.java:55) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226377_(PlacedFeature.java:44) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:466) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ChunkGeneratorMixin,pl:mixin:APP:betterfortresses.mixins.json:DisableVanillaFortressesMixin,pl:mixin:APP:structure_gel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:APP:byg.mixins.json:access.ChunkGeneratorAccess,pl:mixin:APP:betterwitchhuts.mixins.json:DisableVanillaWitchHutsMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:betterstrongholds.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223313_(ChunkStatus.java:145) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:radon.mixins.json:chunk.MixinChunkStatus,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.mdb85312$lambda$injectLightmapSetup$1$4(ChunkStatus.java:546) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:radon.mixins.json:chunk.MixinChunkStatus,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:radon.mixins.json:chunk.MixinChunkStatus,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?] {re:classloading}
	at 
[crash-2023-06-07_16.01.27-server.txt](https://github.com/AllTheMods/ATM-8/files/11675188/crash-2023-06-07_16.01.27-server.txt)

**Comment by ManofLead** [comment]
I get the exact same error when generating chunks in the Nether (and no other time). Setting Chunky to pregen will usually cause this within a minute.

**Comment by liangfan-e** [comment]
may it cause by offline account . the crash seems to disappear after i enable online-mode。

**Comment by liangfan-e** [comment]
No！！！ After using online mode, I encountered this problem again today. This crash should be unrelated to offline accounts

**Comment by lk40games** [comment]
I just encountered this exact same crash less than 2 minutes after entering the nether.
