### ISSUE TITLE
[1.0.21.b] Server timeout when opening Super Wireless Grid

### ISSUE THREAD

**Issue by IEatCodeDaily** [AllTheMods/ATM-8#1493]
ATM8 version: 1.0.21b

 Randomly I get server timeout when trying to open the super wireless grid. After that, the super wireless grid becomes unusable as it will cause server timeout when I try to open it. Crafting and binding a new super wireless grid fixes the problem. However, this phenomenon keeps happening over and over again.

Here's the server log whenever I get server timeout.
 
```
[06:24:33] [Server thread/ERROR] [fastsuite/]: Multithreaded recipe lookup took longer than 25 seconds - aborting and returning nothing. Consider blacklisting this recipe type (minecraft:crafting) in the config.
java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1004)
        at TRANSFORMER/fastsuite@4.1.0/shadows.fastsuite.StreamUtils.executeUntil(StreamUtils.java:104)
        at TRANSFORMER/fastsuite@4.1.0/shadows.fastsuite.AuxRecipeManager.m_44015_(AuxRecipeManager.java:42)
        at TRANSFORMER/rebornstorage@5.0.3/net.gigabit101.rebornstorage.grid.crafting.WirelessCraftingGrid.onCraftingMatrixChanged(WirelessCraftingGrid.java:131)
        at TRANSFORMER/rebornstorage@5.0.3/net.gigabit101.rebornstorage.grid.crafting.WirelessCraftingGrid$1.m_6199_(WirelessCraftingGrid.java:61)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.inventory.CraftingContainer.m_6836_(CraftingContainer.java:63)
        at TRANSFORMER/refinedstorage@1.11.6/com.refinedmods.refinedstorage.apiimpl.network.grid.CraftingGridBehavior.onRecipeTransfer(CraftingGridBehavior.java:216)
        at TRANSFORMER/rebornstorage@5.0.3/net.gigabit101.rebornstorage.grid.crafting.WirelessCraftingGrid.onRecipeTransfer(WirelessCraftingGrid.java:187)
        at TRANSFORMER/refinedstorage@1.11.6/com.refinedmods.refinedstorage.network.grid.GridTransferMessage.lambda$handle$0(GridTransferMessage.java:63)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
        at java.base/java.lang.Thread.run(Thread.java:833)
[06:25:01] [Server thread/ERROR] [fastsuite/]: Multithreaded recipe lookup took longer than 25 seconds - aborting and returning nothing. Consider blacklisting this recipe type (minecraft:crafting) in the config.
java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1004)
        at TRANSFORMER/fastsuite@4.1.0/shadows.fastsuite.StreamUtils.executeUntil(StreamUtils.java:104)
        at TRANSFORMER/fastsuite@4.1.0/shadows.fastsuite.AuxRecipeManager.m_44015_(AuxRecipeManager.java:42)
        at TRANSFORMER/rebornstorage@5.0.3/net.gigabit101.rebornstorage.grid.crafting.WirelessCraftingGrid.onCraftingMatrixChanged(WirelessCraftingGrid.java:131)
        at TRANSFORMER/rebornstorage@5.0.3/net.gigabit101.rebornstorage.grid.crafting.WirelessCraftingGrid$1.m_6199_(WirelessCraftingGrid.java:61)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.inventory.CraftingContainer.m_6836_(CraftingContainer.java:63)
        at TRANSFORMER/refinedstorage@1.11.6/com.refinedmods.refinedstorage.apiimpl.network.grid.CraftingGridBehavior.onRecipeTransfer(CraftingGridBehavior.java:216)
        at TRANSFORMER/rebornstorage@5.0.3/net.gigabit101.rebornstorage.grid.crafting.WirelessCraftingGrid.onRecipeTransfer(WirelessCraftingGrid.java:187)
        at TRANSFORMER/refinedstorage@1.11.6/com.refinedmods.refinedstorage.network.grid.GridTransferMessage.lambda$handle$0(GridTransferMessage.java:63)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
        at java.base/java.lang.Thread.run(Thread.java:833)
[06:25:28] [Server thread/ERROR] [fastsuite/]: Multithreaded recipe lookup took longer than 25 seconds - aborting and returning nothing. Consider blacklisting this recipe type (minecraft:crafting) in the config.
java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1004)
        at TRANSFORMER/fastsuite@4.1.0/shadows.fastsuite.StreamUtils.executeUntil(StreamUtils.java:104)
        at TRANSFORMER/fastsuite@4.1.0/shadows.fastsuite.AuxRecipeManager.m_44015_(AuxRecipeManager.java:42)
        at TRANSFORMER/rebornstorage@5.0.3/net.gigabit101.rebornstorage.grid.crafting.WirelessCraftingGrid.onCraftingMatrixChanged(WirelessCraftingGrid.java:131)
        at TRANSFORMER/rebornstorage@5.0.3/net.gigabit101.rebornstorage.grid.crafting.WirelessCraftingGrid$1.m_6199_(WirelessCraftingGrid.java:61)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.inventory.CraftingContainer.m_6836_(CraftingContainer.java:63)
        at TRANSFORMER/refinedstorage@1.11.6/com.refinedmods.refinedstorage.apiimpl.network.grid.CraftingGridBehavior.onRecipeTransfer(CraftingGridBehavior.java:216)
        at TRANSFORMER/rebornstorage@5.0.3/net.gigabit101.rebornstorage.grid.crafting.WirelessCraftingGrid.onRecipeTransfer(WirelessCraftingGrid.java:187)
        at TRANSFORMER/refinedstorage@1.11.6/com.refinedmods.refinedstorage.network.grid.GridTransferMessage.lambda$handle$0(GridTransferMessage.java:63)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Usually I just brush it off but it becomes more often lately. It even crashed the server once. It seems like it has something to do with recipe?
Crash log attached below.
 
[crash-2023-06-23_06.50.43-server.txt](https://github.com/AllTheMods/ATM-8/files/11841880/crash-2023-06-23_06.50.43-server.txt)

**Comment by IEatCodeDaily** [comment]
Update, it seems to do with Xnet crafting. Similar to issue #1503, #1478, and #1476 .
Tried updating jei-1.19.2-forge-11.6.0.1016.jar and it still crashes.
