### ISSUE TITLE
ATM8 8-1.0.15.  Server crashed and wont launch anymore. stumped- server log inside

### ISSUE THREAD

**Issue by Monkies6669** [AllTheMods/ATM-8#1659]
I was logged on in the world. My son joined in and instantly disconnected.  My computer then lost internet.(not the first time this has happend).  After restart server has failed to launch.  Normally i can figure the issues out but this time i am stumped.

Any help would be appreciated. this is are longest running server and I would really hate to lose it.
[latest.log](https://github.com/AllTheMods/ATM-8/files/12386709/latest.log)

**Comment by TigerWalts** [comment]
The most likely cause is that there is a corrupted config file in the world save: `<world>/serverconfig/corail_woodcutter-server.toml`

```
[19Aug2023 13:10:52.483] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file corail_woodcutter-server.toml of type SERVER for modid corail_woodcutter
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:47) ~[fmlcore-1.19.2-43.2.6.jar%23758!/:?]
	...
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.4.jar%2356!/:?]
	...
```

Delete this file and it will be re-created with the defaults when the server next starts.

This file was probably corrupted when the server initially crashed so you may have another problem after fixing this one.
