### ISSUE TITLE
Crash when farming in an enderman farm

### ISSUE THREAD

**Issue by Mat1tz** [AllTheMods/ATM-8#175]
the game always crashing when i am on my enderman farm

crash log:
[19:41:56] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:164) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:1439) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1223) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.43.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "top.theillusivec4.curios.api.SlotContext.visible()" because the return value of "top.theillusivec4.curios.api.SlotResult.slotContext()" is null
	at twilightforest.compat.curios.CuriosCompat.isSkullCurioEquipped(CuriosCompat.java:126) ~[twilightforest-1.19-4.2.1421-universal.jar%23418!/:4.2.1421]
	at twilightforest.client.TFClientEvents.areCuriosEquipped(TFClientEvents.java:296) ~[twilightforest-1.19-4.2.1421-universal.jar%23418!/:4.2.1421]
	at twilightforest.client.TFClientEvents.unrenderHeadWithTrophies(TFClientEvents.java:284) ~[twilightforest-1.19-4.2.1421-universal.jar%23418!/:4.2.1421]
	at twilightforest.client.__TFClientEvents_unrenderHeadWithTrophies_RenderLivingEvent.invoke(.dynamic) ~[twilightforest-1.19-4.2.1421-universal.jar%23418!/:4.2.1421]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:137) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:45) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at net.minecraft.client.renderer.entity.EndermanRenderer.m_7392_(EndermanRenderer.java:35) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at net.minecraft.client.renderer.entity.EndermanRenderer.m_7392_(EndermanRenderer.java:15) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:136) ~[client-1.19.2-20220805.130853-srg.jar%23436!/:?]
	... 21 more
[19:41:56] [Render thread/FATAL]: Preparing crash report with UUID 4e39c395-d76e-4f2c-826b-eabcd3ce8529
[19:41:56] [Render thread/FATAL]: Preparing crash report with UUID 3b771302-41f0-4f4f-a5a0-2ba5ec892277

**Comment by Mat1tz** [comment]
crashed again, and this time i wasn't even on the farm
