### ISSUE TITLE
A mod tried to access state neighbour directly.

### ISSUE THREAD

**Issue by Pilchh** [AllTheMods/ATM-8#266]
Hello,

I was running the modpack on my server and it was working fine for the past few days. It suddenly crashed and when I tried to relaunch the server I get the following error:

```
Caused by: java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly. Please report this at https://github.com/malte0811/FerriteCore/issues. As a temporary workaround you can enable "populateNeighborTable" in the FerriteCore config
	at TRANSFORMER/ferritecore@5.0.2/malte0811.ferritecore.fastmap.table.CrashNeighborTable.crashOnAccess(CrashNeighborTable.java:101)
	at TRANSFORMER/ferritecore@5.0.2/malte0811.ferritecore.fastmap.table.CrashNeighborTable.rowKeySet(CrashNeighborTable.java:77)
	at TRANSFORMER/canary@0.0.9/com.abdelaziz.canary.common.state.FastImmutableTable.<init>(FastImmutableTable.java:36)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.handler$zmp000$postCreateWithTable(StateHolder.java:528)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.m_61133_(StateHolder.java:1052)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:68)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateDefinition$Builder.m_61101_(StateDefinition.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Block.<init>(Block.java:176)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.AirBlock.<init>(AirBlock.java:12)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:39)
```

The full log is here: [https://pastebin.com/xAkYA6mj](https://pastebin.com/xAkYA6mj)

I have tried to completely reinstall the server (deleting all the files and replacing them with the server files provided by you) but I am still getting this error?

Any ideas what I can do?

Thanks

**Comment by Jonz00r** [comment]
`Please report this at https://github.com/malte0811/FerriteCore/issues. As a temporary workaround you can enable "populateNeighborTable" in the FerriteCore config`

**Comment by Pilchh** [comment]
I have done so, waiting on a reply however, this issue is happening from the default server configs provided by ATM8 so I thought I'd raise it here too.

**Comment by Pilchh** [comment]
After looking into it more, the wrong version of forge was installed.
