### ISSUE TITLE
Cant start server due to error opening jvm args / issue with Unloading server configs

### ISSUE THREAD

**Issue by Cryopticc** [AllTheMods/ATM-8#275]
Hey!
Im having problems making a server. when i try to run the batch file, i get an error saying "could not open `user_jvm_args.txt'"
i have the newest java JRE (1.8.0_351), and both jdk 17(17.0.5) and 19. i was having a lot of issues even installing forge until i got java 19. the tldr here was that nothing at all worked until i got the jdk 19, couldnt even cmd java --version. but i cant get past the error with the jvm args. i tried uninstalling java 19, no luck there. i tried adding a # infront of all args but the ram usage, and still no luck.

ive tried adding the file path before " @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.2-43.1.47/win_args.txt %* " as per instructions but same problem still. did also try and run as admin.

Any ideas of what i can try? cheers :)

**Comment by Cryopticc** [comment]
Update, i did try for some hours before posting this post above, and i am rather tech savy. not a master at batch lines tho, so i searched up and read a little on it. from what i saw in the run batch file, it seemed like i didnt get much info back on what was going on. but i know that in the past, my cmd has been opening sometimes on system32, and i would have to add the directory to the batch file. guess what, i didnt think of this, since i didnt read it in the cmd window. but it worked, i added a " cd C:\Users\XusernameX\Desktop\ATM8 " to the start of the bat file, and it works wonders...

**Comment by Cryopticc** [comment]
Its now stuck at :
" [Server thread/INFO] [configured/]: Unloading server configs... " 
im hoping this just takes a long time? its been sitting like that for a while now, but im going to leave it be for some time and hope that it gets itself going again....

**Comment by Cryopticc** [comment]
turns out its crashing.... 
Description: Exception in server tick loop

java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:626) ~[server-1.19.2-20220805.130853-srg.jar%23384!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23384!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1589) [?:?] {re:mixin}

is the message i got, i keep on testing....

**Comment by Cryopticc** [comment]
Gonna be honest, in true developer syle, i did a lot of things and idk what, but something worked. i deleted a bunch of files (json, toml, configs, the entire world, i reconnected with my internet, and more stuff i cant even remember all of it....) but its working now? soooo im just gonna let it be? 

i guess i solved this myself, but hopefully this info is useful for anyone reading this. devs or fellow players alike.
