### ISSUE TITLE
Server crashing on start

### ISSUE THREAD

**Issue by Shottnor** [AllTheMods/ATM-8#691]
When i try to start the server on my linux mashine, the server crashes almost instantly. The error im getting:

`
[13:54:36] [main/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: null
        Index: 1
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$4576/0x0000000801861508@698075f0
java.util.ConcurrentModificationException
        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
        at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
        at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786)
        at java.base/java.util.Map.forEach(Map.java:703)
        at TRANSFORMER/resourcefulconfig@1.0.17/com.teamresourceful.resourcefulconfig.common.config.forge.ForgeConfigLoader.loadConfig(ForgeConfigLoader.java:119)
        at TRANSFORMER/resourcefulconfig@1.0.17/com.teamresourceful.resourcefulconfig.common.config.forge.ForgeConfigLoader.onConfigLoad(ForgeConfigLoader.java:111)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at LAYER PLUGIN/javafmllanguage@1.19.2-43.2.3/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:42)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.3/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$13(ModContainer.java:150)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.3/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:150)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.3/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.3/net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.3/net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.3/net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50)
        at TRANSFORMER/forge@43.2.3/net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:68)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.3/net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$23(ModLoader.java:207)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.3/net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:207)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.3/net.minecraftforge.fml.ModLoader.lambda$loadMods$17(ModLoader.java:191)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.3/net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:191)
        at TRANSFORMER/forge@43.2.3/net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:33)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Main.main(Main.java:113)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.3/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

[13:54:36] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756) ~[?:?] {}
        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788) ~[?:?] {}
        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786) ~[?:?] {}
        at java.util.Map.forEach(Map.java:703) ~[?:?] {re:mixin}
        at com.teamresourceful.resourcefulconfig.common.config.forge.ForgeConfigLoader.loadConfig(ForgeConfigLoader.java:119) ~[resourcefulconfig-forge-1.19.2-1.0.17.jar%23646!/:?] {re:classloading}
        at com.teamresourceful.resourcefulconfig.common.config.forge.ForgeConfigLoader.onConfigLoad(ForgeConfigLoader.java:111) ~[resourcefulconfig-forge-1.19.2-1.0.17.jar%23646!/:?] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:42) ~[javafmllanguage-1.19.2-43.2.3.jar%23725!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$13(ModContainer.java:150) ~[fmlcore-1.19.2-43.2.3.jar%23724!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:150) ~[fmlcore-1.19.2-43.2.3.jar%23724!/:?] {}
        at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77) ~[fmlcore-1.19.2-43.2.3.jar%23724!/:?] {}
        at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62) ~[fmlcore-1.19.2-43.2.3.jar%23724!/:?] {}
        at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.19.2-43.2.3.jar%23724!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin}
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
        at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.19.2-43.2.3.jar%23724!/:?] {}
        at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:68) ~[forge-1.19.2-43.2.3-universal.jar%23728!/:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$23(ModLoader.java:207) ~[fmlcore-1.19.2-43.2.3.jar%23724!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:207) ~[fmlcore-1.19.2-43.2.3.jar%23724!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$loadMods$17(ModLoader.java:191) ~[fmlcore-1.19.2-43.2.3.jar%23724!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin}
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:191) ~[fmlcore-1.19.2-43.2.3.jar%23724!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:33) ~[forge-1.19.2-43.2.3-universal.jar%23728!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23723!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.3.jar%2367!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
`

running on Ubuntu 22.04 LTS 64bit
tested a normal forge server without mods which starts fine.

**Comment by Mitchell5200** [comment]
I'll need to take a look at the latest.log file from that launch, as there should be something in there about what's causing this crash. 
Please use https://mclo.gs/ for the log file and paste the link back here

**Comment by Shottnor** [comment]
Here ya go:

https://mclo.gs/vesXgGy

Thank you for the quick response :)

**Comment by Shottnor** [comment]
Hi, i found the solution myself. The file access rights on my server where not configured properly. This is not an issue with the pack.

Sorry for taking up your time :)

**Comment by Mightyemperor54** [comment]
Had the same issue as well
