### ISSUE TITLE
Entity Causing crash

### ISSUE THREAD

**Issue by RainbowDonker** [AllTheMods/ATM-8#754]
we have had two from to different mobs from different mods cause crashes.

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_20154_()" because the return value of "com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.m_5448_()" is null
	at com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.findTarget(SculkSnapperEntity.java:277) ~[deeperdarker-forge-1.1.6-forge.jar%23497!/:?] {re:classloading}
	at com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.stateDone(SculkSnapperEntity.java:226) ~[deeperdarker-forge-1.1.6-forge.jar%23497!/:?] {re:classloading}
	at com.kyanite.deeperdarker.miscellaneous.ActionAnimatedEntity.m_8119_(ActionAnimatedEntity.java:105) ~[deeperdarker-forge-1.1.6-forge.jar%23497!/:?] {re:classloading}
	at com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.m_8119_(SculkSnapperEntity.java:126) ~[deeperdarker-forge-1.1.6-forge.jar%23497!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.track(ServerLevel.java:5240) ~[server-1.19.2-20220805.130853-srg.jar%23723!/:?] 

and 

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_20185_()" because "p_24961_" is null
	at net.minecraft.world.entity.ai.control.LookControl.m_24960_(LookControl.java:33) ~[server-1.19.2-20220805.130853-srg.jar%23723!/:?] {re:classloading}
	at com.legacy.blue_skies.entities.hostile.boss.ArachnarchEntity$LungeAtTargetGoal.m_8037_(ArachnarchEntity.java:1163) ~[blue_skies-1.19.2-1.3.20.jar%23454!/:1.3.20] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[server-1.19.2-20220805.130853-srg.jar%23723!/:?] 
{re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119) ~[server-1.19.2-20220805.130853-srg.jar%23723!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:GoalSelectorAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:705) ~[server-1.19.2-20220805.130853-srg.jar%23723!/:?]

**Comment by RainbowDonker** [comment]
if full log is needed let me know and i can provide them

**Comment by RainbowDonker** [comment]
even after update still crashed

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_20154_()" because the return value of "com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.m_5448_()" is null
	at com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.findTarget(SculkSnapperEntity.java:277) ~[deeperdarker-forge-1.1.6-forge.jar%23501!/:?] {re:classloading}
	at com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.stateDone(SculkSnapperEntity.java:226) ~[deeperdarker-forge-1.1.6-forge.jar%23501!/:?] {re:classloading}
	at com.kyanite.deeperdarker.miscellaneous.ActionAnimatedEntity.m_8119_(ActionAnimatedEntity.java:105) ~[deeperdarker-forge-1.1.6-forge.jar%23501!/:?] {re:classloading}
	at com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.m_8119_(SculkSnapperEntity.java:126) ~[deeperdarker-forge-1.1.6-forge.jar%23501!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.track(ServerLevel.java:4740) ~[server-1.19.2-20220805.130853-srg.jar%23729!/:?]

**Comment by Mitchell5200** [comment]
tracked at https://github.com/KyaniteMods/DeeperAndDarker/issues/128
