### ISSUE TITLE
journeymap crashing

### ISSUE THREAD

**Issue by bbarry** [AllTheMods/ATM-8#797]
I just came back home from a trip to the nether and now my game is crashing after I hang out in base for a minute...

```
[21:22:32] [Server thread/INFO] [journeymap/]: Mapping halted in C:\Users\Bill\AppData\Local\.ftba\instances\59e0f98d-eec4-4703-baa8-982799bf1975\journeymap\data\sp\New World\minecraft:overworld
[21:22:32] [Server thread/ERROR] [journeymap/]: [ClientAPI] Error removing all displayables: Marker
java.lang.ClassCastException: class journeymap.client.api.display.MarkerOverlay cannot be cast to class journeymap.client.api.display.PolygonOverlay (journeymap.client.api.display.MarkerOverlay and journeymap.client.api.display.PolygonOverlay are in module journeymap@5.9.0 of loader 'TRANSFORMER' @42e202d7)
	at journeymap.client.api.impl.PluginWrapper.removeAll(PluginWrapper.java:268) ~[journeymap-1.19.2-5.9.0-forge.jar%23643!/:1.19.2-5.9.0] {re:classloading}
	at journeymap.client.api.impl.ClientAPI.removeAll(ClientAPI.java:199) ~[journeymap-1.19.2-5.9.0-forge.jar%23643!/:1.19.2-5.9.0] {re:classloading}
	at journeymap.client.api.impl.ClientAPI.removeAll(ClientAPI.java:216) ~[journeymap-1.19.2-5.9.0-forge.jar%23643!/:1.19.2-5.9.0] {re:classloading}
	at frankv.jmi.JMIJourneyMapPlugin.onEvent(JMIJourneyMapPlugin.java:55) ~[jmi-forge-1.19.2-0.13-30.jar%23642!/:0.13-30] {re:classloading}
	at journeymap.client.api.impl.PluginWrapper.notify(PluginWrapper.java:374) ~[journeymap-1.19.2-5.9.0-forge.jar%23643!/:1.19.2-5.9.0] {re:classloading}
	at journeymap.client.api.impl.ClientEventManager.fireMappingEvent(ClientEventManager.java:81) ~[journeymap-1.19.2-5.9.0-forge.jar%23643!/:1.19.2-5.9.0] {re:classloading}
	at journeymap.client.JourneymapClient.stopMapping(JourneymapClient.java:608) ~[journeymap-1.19.2-5.9.0-forge.jar%23643!/:1.19.2-5.9.0] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at journeymap.client.event.handlers.WorldEventHandler.onUnload(WorldEventHandler.java:32) ~[journeymap-1.19.2-5.9.0-forge.jar%23643!/:1.19.2-5.9.0] {re:classloading}
	at journeymap.client.event.forge.ForgeWorldEvent.onUnload(ForgeWorldEvent.java:19) ~[journeymap-1.19.2-5.9.0-forge.jar%23643!/:1.19.2-5.9.0] {re:classloading}
	at journeymap.client.event.forge.__ForgeWorldEvent_onUnload_Unload.invoke(.dynamic) ~[journeymap-1.19.2-5.9.0-forge.jar%23643!/:1.19.2-5.9.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:580) ~[client-1.19.2-20220805.130853-srg.jar%23805!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_7041_(IntegratedServer.java:173) ~[client-1.19.2-20220805.130853-srg.jar%23805!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:682) ~[client-1.19.2-20220805.130853-srg.jar%23805!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23805!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
```

**Comment by bbarry** [comment]
updating journeymap 5.9.2 fixes this
