### ISSUE TITLE
startup error? KUBE.JS

### ISSUE THREAD

**Issue by demethan** [AllTheMods/ATM-8#908]
Hi, 

I am hitting an issue with the server package 1.0.10.  It is complaining about a kube js script error and crashes. 

I downloaded the latest version of the pack.  I deleted the kube.js folder and uploaded it twice. 

Any idea what is going on?

here is the error part of the  logs/kubejs/startup.txt

```
! [18:21:22] [ERR] Error loading KubeJS script: startup_scripts:script.js': Line 86: 'onEvent()' is no longer supported! Read more on wiki: https://kub>
[18:21:22] [ERR  ] Line 86: 'onEvent()' is no longer supported! Read more on wiki: https://kubejs.com/kjs6
[18:21:22] [ERR  ]      at TRANSFORMER/kubejs@1902.6.0-build.140/dev.latvian.mods.kubejs.util.LegacyCodeHandler.makeError(LegacyCodeHandler.java:29)
[18:21:22] [ERR  ]      at TRANSFORMER/kubejs@1902.6.0-build.140/dev.latvian.mods.kubejs.util.LegacyCodeHandler.call(LegacyCodeHandler.java:34)
[18:21:22] [ERR  ]      at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:1086)
[18:21:22] [ERR  ]      at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:423)
[18:21:22] [ERR  ]      at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[18:21:22] [ERR  ]      at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.Context.doTopCall(Context.java:1197)
[18:21:22] [ERR  ]      at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:2619)
[18:21:22] [ERR  ]      at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.InterpretedFunction.exec(InterpretedFunction.java:83)
[18:21:22] [ERR  ]      at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.Context.evaluateString(Context.java:615)
[18:21:22] [ERR  ]      at TRANSFORMER/kubejs@1902.6.0-build.140/dev.latvian.mods.kubejs.script.ScriptFile.load(ScriptFile.java:22)
[18:21:22] [ERR  ]      at TRANSFORMER/kubejs@1902.6.0-build.140/dev.latvian.mods.kubejs.script.ScriptManager.load(ScriptManager.java:195)
[18:21:22] [ERR  ]      at TRANSFORMER/kubejs@1902.6.0-build.140/dev.latvian.mods.kubejs.script.ScriptManager.reload(ScriptManager.java:74)
[18:21:22] [ERR  ]      at TRANSFORMER/kubejs@1902.6.0-build.140/dev.latvian.mods.kubejs.KubeJS.<init>(KubeJS.java:134)
[18:21:22] [ERR  ]      at TRANSFORMER/kubejs@1902.6.0-build.140/dev.latvian.mods.kubejs.forge.KubeJSForge.<init>(KubeJSForge.java:29)
[18:21:22] [ERR  ]      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:21:22] [ERR  ]      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[18:21:22] [ERR  ]      at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:21:22] [ERR  ]      at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:21:22] [ERR  ]      at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:21:22] [ERR  ]      at LAYER PLUGIN/javafmllanguage@1.19.2-43.2.3/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.ja>
[18:21:22] [ERR  ]      at LAYER PLUGIN/fmlcore@1.19.2-43.2.3/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:12>
[18:21:22] [ERR  ]      at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[18:21:22] [ERR  ]      at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[18:21:22] [ERR  ]      at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[18:21:22] [ERR  ]      at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[18:21:22] [ERR  ]      at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[18:21:22] [ERR  ]      at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[18:21:22] [ERR  ]      at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[18:21:22] [INFO ] Loaded 5/6 KubeJS startup scripts in 0.607 s

```

**Comment by enigmaquip** [comment]
You have some incorrect files mixed in. We don't have a file named `script.js` in startup_scripts. Kubejs will make that file automatically if the kubejs folder is empty on first run, but it also wouldn't make a file with `onEvent()` as that's a 1.18 method for kjs that is not used in 1.19

**Comment by demethan** [comment]
ya.. sorry about the post.. previous server was on 1.18 and libraries were conflicting.
